### ISSUE TITLE
Divisor de tensao e botao

### ISSUE THREAD

**Issue by elfotux** [raulhackerclub/RHi-hacker#1]
Criar trilhas para os botoes, sendo que utilizaremos kicad para confeccionar a placa de circuito

**Comment by zecarhc** [comment]
Na verdade, aqui é a Issue que se refere ao mini projeto de encaixar uma peça e fazer um led acender a depender se tiver a peça encaixada ou não, e além disso, printar no monitor serial se o encaixe tem peça ou está vazio.

**Comment by zecarhc** [comment]
Fiz um esquema no Tinkercad para implementar o código:  https://www.tinkercad.com/things/7PYprOQq64w

**Comment by zecarhc** [comment]
E aqui tá o código pra quem quiser replicar: 978e89c

**Comment by zecarhc** [comment]
E aqui tá o código pra quem quiser replicar: 978e89c
