### ISSUE TITLE
Arquivo com sugestões para projeto final

### ISSUE THREAD

**Issue by zecarhc** [raulhackerclub/RHi-hacker#4]
Criar um arquivo .txt em que todos possam fazer sugestões e incluir funcionalidades, design, qualquer coisa que se refira a alguma implementação do produto final.

**Comment by zecarhc** [comment]
Arquivo criado em: 1ac9a24

**Comment by firefueled** [comment]
@zecarhc, acho melhor criar o arquivo de sugestões, ou qualquer outra coisa não relacionada ao software, dentro do Wiki. [Como está página de sugestões](https://github.com/raulhackerclub/RHi-hacker/wiki/Sugest%C3%B5es).
Caso seja melhor criar arquivos de texto dentro do repositório de código, é melhor que o criem com o formato [Markdown](https://github.com/luong-komorebi/Markdown-Tutorial/blob/master/README_pt-BR.md) (.md).
